# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biero', '0002_auto_20160506_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('courriel', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='biere',
            name='image',
            field=models.FileField(default='default.png', upload_to=b''),
        ),
    ]
