# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biero', '0003_auto_20160506_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biere',
            old_name='timestamp',
            new_name='ajoute',
        ),
    ]
