# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biero', '0005_auto_20160506_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biere',
            name='image',
            field=models.FileField(default='default.png', upload_to='bieres'),
        ),
    ]
