# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biero', '0009_auto_20160516_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='biere',
            name='pays',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biere',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='bieres/'),
        ),
    ]
