# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biero', '0011_commentaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='ajoute',
            new_name='ajouteCommentaire',
        ),
    ]
