# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biero', '0016_auto_20160529_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usager',
            name='courriel',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
