# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biero', '0018_auto_20160530_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usager',
            name='username',
            field=models.CharField(max_length=256),
        ),
    ]
