# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biero', '0019_auto_20160530_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usager',
            old_name='username',
            new_name='nomUsager',
        ),
    ]
